import { MetadataRoute } from 'next'

export const dynamic = 'force-static'

/**
 * robots.txt, generated by Next alongside app/sitemap.ts.
 *
 * It used to come from next-sitemap's `generateRobotsTxt`, which writes into
 * public/ in a postbuild step — but this site is `output: 'export'` into dist/,
 * and public/ has already been copied by then, so the file never shipped and
 * the live URL returned 404. Nothing declared the sitemap to crawlers.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: '*',
      allow: '/',
    },
    sitemap: 'https://paulaviena.com/sitemap.xml',
    host: 'https://paulaviena.com',
  }
}
